apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db-password: {{ .Values.postgresql.password | quote }}
  redis-password: {{ .Values.redis.password | default "" | quote }}
  jwt-secret: {{ .Values.backend.env.JWT_SECRET | quote }}
  internal-token: {{ .Values.backend.env.INTERNAL_TOKEN | default "" | quote }}
  mail-password: {{ .Values.backend.env.MAIL_PASSWORD | default "" | quote }}
  google-client-secret: {{ .Values.backend.env.GOOGLE_CLIENT_SECRET | default "" | quote }}
  yandex-client-secret: {{ .Values.backend.env.YANDEX_CLIENT_SECRET | default "" | quote }}