apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | default "changeme" | quote }}
  redis-password: {{ .Values.secrets.redisPassword | default "" | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | default "change-me-in-production-min-32-chars-long!!" | quote }}
  mail-password: {{ .Values.secrets.mailPassword | default "" | quote }}
  google-client-secret: {{ .Values.secrets.googleClientSecret | default "" | quote }}
  yandex-client-secret: {{ .Values.secrets.yandexClientSecret | default "" | quote }}
